flowchart TD
    HomePage["HomePage"]
    BackgroundShapes["BackgroundShapes"]
    FloatingChatButton["FloatingChatButton"]
    HeaderContainer["HeaderContainer"]
    TopBar["TopBar"]
    AvatarSection["AvatarSection"]
    GreetingSection["GreetingSection"]
    TipsCarousel["TipsCarousel"]
    WidgetsContainer["WidgetsContainer"]

    AnnouncementWidget["AnnouncementWidget"]
    AnnouncementPage["AnnouncementPage"]

    HabitsWidget["HabitsWidget"]
    HabitsPage["HabitsPage"]
    HabitsTopButtons["HabitsTopButtons"]
    HabitsListContainer["HabitsListContainer"]
    HabitCard["HabitCard"]
    HabitCardBack["HabitCardBack"]

    TodosWidget["TodosWidget"]
    TodosPage["TodosPage"]
    TodosTopButtons["TodosTopButtons"]
    TodoListContainer["TodoListContainer"]
    TodoCard["TodoCard"]
    TodoCardBack["TodoCardBack"]

    SuccessCoachWidget["SuccessCoachWidget"]
    SuccessCoachPage["SuccessCoachPage"]

    AnalyticsWidget["AnalyticsWidget"]
    AnalyticsPage["AnalyticsPage"]

    LifeScoreWidget["LifeScoreWidget"]
    LifeScorePage["LifeScorePage"]

    AchievementsWidget["AchievementsWidget"]
    AchievementsPage["AchievementsPage"]

    AdsCarouselWidget["AdsCarouselWidget"]
    ShopCoursesWidgets["ShopCoursesWidgets"]

    HomePage --> BackgroundShapes
    HomePage --> FloatingChatButton
    HomePage --> HeaderContainer
    HomePage --> WidgetsContainer

    HeaderContainer --> TopBar
    HeaderContainer --> AvatarSection
    HeaderContainer --> GreetingSection
    HeaderContainer --> TipsCarousel

    WidgetsContainer --> AnnouncementWidget
    WidgetsContainer --> HabitsWidget
    WidgetsContainer --> TodosWidget
    WidgetsContainer --> SuccessCoachWidget
    WidgetsContainer --> AnalyticsWidget
    WidgetsContainer --> LifeScoreWidget
    WidgetsContainer --> AchievementsWidget
    WidgetsContainer --> AdsCarouselWidget
    WidgetsContainer --> ShopCoursesWidgets

    AnnouncementWidget --> AnnouncementPage

    HabitsWidget --> HabitsPage
    HabitsPage --> HabitsTopButtons
    HabitsPage --> HabitsListContainer
    HabitsListContainer --> HabitCard
    HabitCard --> HabitCardBack

    TodosWidget --> TodosPage
    TodosPage --> TodosTopButtons
    TodosPage --> TodoListContainer
    TodoListContainer --> TodoCard
    TodoCard --> TodoCardBack

    SuccessCoachWidget --> SuccessCoachPage
    AnalyticsWidget --> AnalyticsPage
    LifeScoreWidget --> LifeScorePage
    AchievementsWidget --> AchievementsPage